#!/usr/bin/env bash
# Module Intelligence System (MIS) — Contract Initializer
# Scans repo and generates initial module contracts (API, DB, Events, Dependencies)
set -eo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log_info() { echo -e "${BLUE}[INFO]${NC} $*"; }
log_success() { echo -e "${GREEN}[OK]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*" >&2; }

REPO_PATH="${1:-.}"
REPO_PATH="$(cd "$REPO_PATH" && pwd)"

if [[ ! -d "$REPO_PATH/.git" ]]; then
  log_error "Not a git repository: $REPO_PATH"
  exit 1
fi

CONTRACT_DIR="$REPO_PATH/.sdlc/module-contracts"
mkdir -p "$CONTRACT_DIR"

TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
COMMIT_HASH=$(cd "$REPO_PATH" && git rev-parse HEAD 2>/dev/null || echo "unknown")
MODULE_NAME=$(basename "$REPO_PATH")

log_info "Initializing Module Intelligence System for: $REPO_PATH"
log_info "Module name: $MODULE_NAME"
log_info "Output directory: $CONTRACT_DIR"
echo ""

# ============================================================================
# DETECT STACK
# ============================================================================

detect_stack() {
  local has_pom=0
  local has_gradle=0
  local has_package_json=0
  local has_metro=0
  local has_makefile=0

  [[ -f "$REPO_PATH/pom.xml" ]] && has_pom=1
  [[ -f "$REPO_PATH/build.gradle" || -f "$REPO_PATH/build.gradle.kts" ]] && has_gradle=1
  [[ -f "$REPO_PATH/package.json" ]] && has_package_json=1
  [[ -f "$REPO_PATH/metro.config.js" ]] && has_metro=1
  [[ -f "$REPO_PATH/Makefile" || -f "$REPO_PATH/CMakeLists.txt" ]] && has_makefile=1

  if [[ $has_pom -eq 1 || $has_gradle -eq 1 ]]; then
    echo "java"
  elif [[ $has_package_json -eq 1 && $has_metro -eq 1 ]]; then
    echo "react-native"
  elif [[ $has_package_json -eq 1 ]]; then
    echo "node"
  elif [[ $has_makefile -eq 1 ]]; then
    echo "c"
  else
    echo "unknown"
  fi
}

STACK=$(detect_stack)
log_success "Detected stack: $STACK"
echo ""

# ============================================================================
# EXTRACT API ENDPOINTS (Java only for now)
# ============================================================================

extract_api_endpoints() {
  log_info "Scanning for API endpoints..."
  local endpoints=()

  if [[ "$STACK" == "java" ]]; then
    # Find @RequestMapping, @PostMapping, @GetMapping, @PutMapping, @DeleteMapping
    find "$REPO_PATH/src/main/java" -name "*.java" 2>/dev/null | while read -r file; do
      grep -n "@\(Request\|Get\|Post\|Put\|Delete\|Patch\)Mapping" "$file" 2>/dev/null | head -5
    done | head -20
  fi
}

# ============================================================================
# EXTRACT DATABASE TABLES (from migrations)
# ============================================================================

extract_db_tables() {
  log_info "Scanning for database migrations..."
  local migrations=()

  find "$REPO_PATH" -path "*/db/migrations/*.sql" -o -path "*/src/main/resources/db/migration/*.sql" 2>/dev/null | head -10
}

# ============================================================================
# EXTRACT KAFKA TOPICS
# ============================================================================

extract_kafka_topics() {
  log_info "Scanning for Kafka topics..."

  if [[ "$STACK" == "java" ]]; then
    grep -r "\.topic\|@KafkaListener\|KafkaTemplate\|KafkaProducer" \
      "$REPO_PATH/src/main/java" "$REPO_PATH/src/main/resources" 2>/dev/null | head -20 || true
  fi
}

# ============================================================================
# EXTRACT EXTERNAL DEPENDENCIES
# ============================================================================

extract_dependencies() {
  log_info "Scanning for external dependencies..."

  if [[ -f "$REPO_PATH/pom.xml" ]]; then
    grep -A 2 "<dependency>" "$REPO_PATH/pom.xml" 2>/dev/null | grep -E "<groupId>|<artifactId>" | head -20
  elif [[ -f "$REPO_PATH/build.gradle" || -f "$REPO_PATH/build.gradle.kts" ]]; then
    grep -E "implementation|api|compileOnly" "$REPO_PATH/build.gradle"* 2>/dev/null | head -20
  elif [[ -f "$REPO_PATH/package.json" ]]; then
    cat "$REPO_PATH/package.json" | grep -E '"(dependencies|devDependencies)"' -A 20 | head -30
  fi
}

# ============================================================================
# CREATE API CONTRACT TEMPLATE
# ============================================================================

create_api_contract() {
  log_info "Creating API contract..."
  local contract_file="$CONTRACT_DIR/api-contract.yaml"

  cat > "$contract_file" << 'EOF'
# Module API Contract
# Generated by MIS — Review and complete this file before use

version: "1.0"
module: MODULE_NAME_HERE
base_path: /api/v1

# ENDPOINTS — Add your API endpoints here
# Example format:
# endpoints:
#   - path: /users
#     method: POST
#     summary: Create user
#     request_schema: CreateUserRequest
#     response_schema: UserResponse
#     status_codes: [201, 400, 409]
#     breaking_change_notes: null
#     consumers: []
#
#   - path: /users/{id}
#     method: GET
#     summary: Fetch user by ID
#     response_schema: UserResponse
#     status_codes: [200, 404]
#     consumers: []

endpoints: []

# REQUEST/RESPONSE SCHEMAS
# Define all request and response objects here
schemas: {}

# DEPRECATIONS — List deprecated endpoints
deprecations: []

# NOTES FOR DEVELOPERS
# - Run `git log --oneline --grep="API\|endpoint" | head -20` to find recent API changes
# - Check @RequestMapping, @PostMapping, @GetMapping in source code
# - Identify all request/response DTOs
# - List all services that consume your APIs
# - Document any breaking changes with migration guides

notes: |
  To complete this contract:
  1. Review all @RequestMapping annotations in controllers
  2. Document request/response schemas for each endpoint
  3. Add all known consumers of each endpoint
  4. Identify any deprecated endpoints (especially from old versions)
  5. Add migration guides for breaking changes
  6. Include status codes and error responses
  7. Document authentication and authorization requirements
EOF

  log_success "Created: api-contract.yaml"
}

# ============================================================================
# CREATE DATA CONTRACT TEMPLATE
# ============================================================================

create_data_contract() {
  log_info "Creating data contract..."
  local contract_file="$CONTRACT_DIR/data-contract.yaml"

  cat > "$contract_file" << 'EOF'
# Module Data Contract
# Generated by MIS — Review and complete this file before use

version: "1.0"
database: postgresql

# TABLES — Define all database tables here
# Example format:
# tables:
#   users:
#     columns:
#       id: {type: bigserial, primary_key: true, immutable: true}
#       email: {type: varchar(255), unique: true, required: true}
#       created_at: {type: timestamp, immutable: true}
#       updated_at: {type: timestamp}
#     indexes:
#       - name: idx_users_email
#         columns: [email]
#         unique: true
#     foreign_keys:
#       - column: organization_id
#         references: organizations.id
#         on_delete: cascade

tables: {}

# MIGRATIONS — Track all schema changes
# migrations:
#   - version: "001"
#     description: "Create users table"
#     file: "db/migrations/001_create_users.sql"
#     tested: true
#     rolled_back: true
#   - version: "002"
#     description: "Add email unique index"
#     file: "db/migrations/002_add_email_index.sql"
#     tested: true
#     rolled_back: false

migrations: []

# COLUMN IMMUTABILITY — Define which columns cannot be modified
readonly_columns: []
mutable_columns: []

# BREAKING CHANGES — Document any breaking changes to schema
breaking_changes: []

# NOTES FOR DEVELOPERS
# - Review all migration files in db/migrations/
# - Document each table's purpose and relationships
# - Mark immutable columns (id, created_at, etc.)
# - Include all indexes and foreign keys
# - Test all migrations can be rolled back
# - Document breaking changes with migration guides

notes: |
  To complete this contract:
  1. Review migration files in db/migrations/
  2. Document all table structures
  3. List all indexes and constraints
  4. Identify foreign key relationships
  5. Mark immutable vs. mutable columns
  6. Test each migration's rollback capability
  7. Document any breaking schema changes with migration paths
EOF

  log_success "Created: data-contract.yaml"
}

# ============================================================================
# CREATE EVENT CONTRACT TEMPLATE
# ============================================================================

create_event_contract() {
  log_info "Creating event contract..."
  local contract_file="$CONTRACT_DIR/event-contract.yaml"

  cat > "$contract_file" << 'EOF'
# Module Event Contract
# Generated by MIS — Review and complete this file before use

version: "1.0"
broker: kafka
namespace: jio.services.MODULE_NAME_HERE

# EVENTS PRODUCED — Events this service publishes
# events_produced:
#   - name: user.created
#     topic: user.created.v1
#     version: "1"
#     schema:
#       user_id: {type: string, format: uuid}
#       email: {type: string}
#       timestamp: {type: timestamp}
#     produced_by: [CreateUserController]
#     consumed_by: [analytics-service, notification-service]
#     retention: 7d

events_produced: []

# EVENTS CONSUMED — Events this service listens to
# events_consumed:
#   - name: organization.deleted
#     topic: org.deleted.v1
#     consumed_by: [DeleteUsersByOrgController]
#     expected_frequency: "rare (<1/hour)"
#     timeout_action: "log and skip"

events_consumed: []

# BREAKING CHANGES — Breaking changes to event schemas
# breaking_changes:
#   - event: user.created
#     version: "1.0 → 2.0"
#     change: "Added phone_number field (optional)"
#     impact: "Old consumers still work (field is optional)"
#     migration_deadline: null

breaking_changes: []

# NOTES FOR DEVELOPERS
# - Find Kafka topics in application.properties and application.yml
# - Search for @KafkaListener and KafkaTemplate usage
# - Document event producers (which classes publish)
# - Document event consumers (which services listen)
# - Include event schema details
# - Add retention policies
# - Document breaking changes with migration deadlines

notes: |
  To complete this contract:
  1. Find all Kafka topics in config files
  2. Document event schema for each topic
  3. Identify which services produce/consume each event
  4. Set retention policies for each event
  5. Document breaking changes with impact analysis
  6. Include migration deadlines for breaking changes
  7. Test event schema validation
EOF

  log_success "Created: event-contract.yaml"
}

# ============================================================================
# CREATE DEPENDENCIES CONTRACT TEMPLATE
# ============================================================================

create_dependencies_contract() {
  log_info "Creating dependencies contract..."
  local contract_file="$CONTRACT_DIR/dependencies.yaml"

  cat > "$contract_file" << 'EOF'
# Module Dependencies Contract
# Generated by MIS — Review and complete this file before use

version: "1.0"
module: MODULE_NAME_HERE

# EXTERNAL SERVICES — Services this module depends on
# external_services:
#   - service: auth-service
#     endpoints: [/auth/validate]
#     purpose: "Validate OAuth tokens"
#     failure_mode: "Return 401 Unauthorized"
#     sla: "99.9%"
#     backup_available: true
#
#   - service: notification-service
#     events_published_to: [user.created, user.email_changed]
#     purpose: "Send emails on user lifecycle events"
#     failure_mode: "Async — failures queued for retry"

external_services: []

# INTERNAL MODULES — Other modules this depends on
# internal_modules:
#   - module: user-repository
#     use: "Database access layer"
#     breaking_changes_tracked: true

internal_modules: []

# LIBRARIES — Third-party libraries and their constraints
# libraries:
#   - name: spring-security
#     version: "6.1.0"
#     purpose: "OAuth2 provider"
#     security_constraint: true
#     cve_tracked: true

libraries: []

# NOTES FOR DEVELOPERS
# - Check all @FeignClient and RestTemplate usage
# - Review application.properties for service URLs
# - Document all HTTP/gRPC clients to external services
# - List all internal module imports
# - Check pom.xml/build.gradle for critical dependencies
# - Document failure modes and fallbacks
# - Include SLA requirements for each dependency

notes: |
  To complete this contract:
  1. Find all external service calls (FeignClient, RestTemplate, etc.)
  2. Document each service's endpoints and purpose
  3. Define failure modes and fallback behavior
  4. Document SLA requirements
  5. List all internal module imports
  6. Identify critical libraries with security constraints
  7. Document which dependencies are breaking-change tracked
EOF

  log_success "Created: dependencies.yaml"
}

# ============================================================================
# CREATE BREAKING CHANGES GUIDE
# ============================================================================

create_breaking_changes_guide() {
  log_info "Creating breaking changes guide..."
  local guide_file="$CONTRACT_DIR/breaking-changes.md"

  cat > "$guide_file" << 'EOF'
# Breaking Change Policy for MODULE_NAME_HERE

## What is a Breaking Change?

A breaking change is any modification that requires consumers to update their code:

### API Breaking Changes
- Endpoint removed or renamed
- Required request field added
- Required response field removed or renamed
- Response field type changed
- Status code behavior changed

### Data Breaking Changes
- Column removed from database
- Column type changed (e.g., int → varchar)
- Unique constraint added to column with duplicates
- Foreign key added (integrity constraint)
- Column made required (null → not null)

### Event Breaking Changes
- Event topic removed or renamed
- Required field removed from schema
- Required field type changed
- Required field added (old producers fail)

## What is NOT a Breaking Change?

- Optional field added to request (old clients work)
- Optional field added to response (old clients ignore)
- New optional query parameter
- New event topic (if old topic stays)
- Column added to database (nullable)
- Additional status codes in API response
- New optional event field (backward compatible)

## Approval Workflow

1. **Identify the change** — Determine if it's breaking
2. **Document it** — Add to this file with details
3. **Create ADO issue** — Link with `AB#XXXXX` in commit
4. **Notify consumers** — Contact all consuming services
5. **Set deadline** — Usually 6 months from change date
6. **Merge after approval** — Get stakeholder sign-off
7. **Enforce deadline** — Remove deprecated code at deadline

## Current Breaking Changes

**None** (as of TIMESTAMP_HERE)

## Planned Breaking Changes

Add planned changes here with deprecation dates.

## Past Breaking Changes (History)

Include history of removed breaking changes:
- What changed
- When it was deprecated
- When it was removed
- How consumers were impacted

## Migration Guides

Create subdirectories for each breaking change:
- `migration/v2.0-api-changes.md` — Guide for API consumers
- `migration/v2.0-schema-changes.md` — Guide for DB migrations
- `migration/v2.0-event-changes.md` — Guide for event consumers

## Contact

For breaking change questions, contact:
- Service Owner: [NAME_HERE]
- Architecture: [TEAM_HERE]
EOF

  log_success "Created: breaking-changes.md"
}

# ============================================================================
# CREATE SUMMARY AND NEXT STEPS
# ============================================================================

create_summary() {
  log_info "Generating summary..."
  local summary_file="$CONTRACT_DIR/SUMMARY.md"

  cat > "$summary_file" << EOF
# Module Intelligence System (MIS) — Contract Summary

## Module: $MODULE_NAME
**Generated:** $TIMESTAMP
**Commit:** $COMMIT_HASH
**Stack:** $STACK

## Contracts Created

1. **api-contract.yaml** — API endpoint contract
   - Define all REST endpoints
   - Document request/response schemas
   - List API consumers
   - Track deprecations

2. **data-contract.yaml** — Database schema contract
   - Document table structures
   - Track migrations
   - Mark immutable columns
   - Document breaking changes

3. **event-contract.yaml** — Event schema contract
   - Define Kafka topics
   - Document event schemas
   - List producers/consumers
   - Track breaking changes

4. **dependencies.yaml** — External dependency contract
   - List external services
   - Document internal modules
   - Track critical libraries
   - Define SLAs

5. **breaking-changes.md** — Breaking change policy
   - Define what breaks
   - Approval workflow
   - Migration guides
   - History tracking

## Next Steps

### 1. Review and Complete Contracts
- [ ] Fill in api-contract.yaml with your endpoints
- [ ] Document all request/response schemas
- [ ] Fill in data-contract.yaml with table definitions
- [ ] Complete event-contract.yaml with Kafka topics
- [ ] List all dependencies in dependencies.yaml
- [ ] Update breaking-changes.md with policy

### 2. Validate Contracts
Run validation to check contract syntax:
\`\`\`bash
sdlc mis validate
\`\`\`

### 3. Analyze Changes
When making changes, analyze impact:
\`\`\`bash
sdlc mis analyze-change <branch-name>
\`\`\`

### 4. Pre-Merge Validation
Before merging, validate against contracts:
\`\`\`bash
sdlc mis validate-merge
\`\`\`

## Scanning Tips

### Find API Endpoints
\`\`\`bash
grep -r "@RequestMapping\|@PostMapping\|@GetMapping" src/main/java
\`\`\`

### Find Migrations
\`\`\`bash
find . -path "*/db/migrations/*.sql" -o -path "*/migration/*.sql"
\`\`\`

### Find Kafka Topics
\`\`\`bash
grep -r "KafkaTemplate\|@KafkaListener\|topics\|\.topic" src/
\`\`\`

### Find External Services
\`\`\`bash
grep -r "@FeignClient\|RestTemplate\|WebClient" src/
\`\`\`

## Commands

\`\`\`bash
# Initialize MIS (this script)
sdlc mis init [repo-path]

# Show contracts
sdlc mis show api
sdlc mis show data
sdlc mis show events

# Analyze changes on branch
sdlc mis analyze-change [branch-name]

# Validate contracts before merge
sdlc mis validate-merge

# Generate impact report
sdlc mis impact-report
\`\`\`

## Resources

- Module Knowledgebase: `.sdlc/module-kb/`
- Contracts: `.sdlc/module-contracts/`
- Change Analysis: `.sdlc/module-contracts/last-change-analysis.json`
- Impact Reports: `.sdlc/module-contracts/impact-reports/`

---

**Platform:** AI SDLC Platform v2.0
**Module Intelligence System Version:** 1.0
EOF

  log_success "Created: SUMMARY.md"
}

# ============================================================================
# MAIN EXECUTION
# ============================================================================

create_api_contract
create_data_contract
create_event_contract
create_dependencies_contract
create_breaking_changes_guide
create_summary

echo ""
log_success "Module Intelligence System initialized at: $CONTRACT_DIR"
echo ""
log_info "Next steps:"
echo "  1. Review .sdlc/module-contracts/*.yaml"
echo "  2. Fill in contract details with your module specifics"
echo "  3. Run 'sdlc mis validate' to check syntax"
echo "  4. Run 'sdlc mis analyze-change <branch>' to test change analysis"
echo ""
log_info "For help: cat $CONTRACT_DIR/SUMMARY.md"
