#!/usr/bin/env bash
# verify-claude-ssot-ci.sh — Enforce single source of truth for .claude/ mirrors.
# Accepts two valid layouts (cross-platform: Mac + Windows team):
#   (1) Symlink mode      — .claude/<name> is a symlink to ../<name>   (Mac/Linux native)
#   (2) Generated-copy    — .claude/<name> is a directory byte-identical to <name>/
#                           (regenerated by scripts/sync-claude-mirrors.sh; safe on Windows)
# Fails CI if drift exists. Local dev: no-op unless GITHUB_ACTIONS is set (run manually
# with FORCE=1 to validate locally).
# Usage: bash scripts/verify-claude-ssot-ci.sh [platform-root]

set -euo pipefail

ROOT="${1:-.}"
ROOT="$(cd "$ROOT" && pwd)"

if [[ -z "${GITHUB_ACTIONS:-}" && -z "${FORCE:-}" ]]; then
  exit 0
fi

fail() {
  echo "::error::$*"
  exit 1
}

DRIFT=0
for name in agents skills templates; do
  canonical="${ROOT}/${name}"
  mirror="${ROOT}/.claude/${name}"
  [[ -e "$mirror" ]] || continue
  [[ -d "$canonical" ]] || { echo "[warn] canonical ${name}/ missing — skipping"; continue; }

  if [[ -L "$mirror" ]]; then
    echo "[ok] .claude/${name} → symlink mode"
    continue
  fi

  if [[ -d "$mirror" ]]; then
    # Generated-copy mode: must be byte-identical to canonical tree
    if diff -rq "$canonical" "$mirror" > /tmp/claude_ssot_drift_${name}.txt 2>&1; then
      echo "[ok] .claude/${name} → generated-copy mode (no drift)"
    else
      echo "::error::.claude/${name} drift detected. Canonical tree is ${name}/. Regenerate with: bash scripts/sync-claude-mirrors.sh"
      echo "--- drift report ---"
      cat /tmp/claude_ssot_drift_${name}.txt
      echo "--------------------"
      DRIFT=1
    fi
  fi
done

if [[ "$DRIFT" -ne 0 ]]; then
  fail "One or more .claude/ mirrors drifted from canonical trees."
fi

echo "verify-claude-ssot-ci: OK"
